---
- name: Get facts and create report
  hosts: all
  tasks:
  - napalm_get_facts:
      hostname={{ansible_host}}
      username={{ansible_user}}
      password={{ansible_ssh_pass}}
      dev_os={{ansible_network_os}}
      filter='facts,interfaces,interfaces_ip'
  - template: src="report.j2" dest="report.htm"
